matrix:
  include:
    - language: python
      python: '3.7'
      dist: xenial
      os: linux

install:
  - mkdir nvim-nightly
  - |
    curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
    tar xzf nvim-linux64.tar.gz -C ./nvim-nightly
  - |
    python3 -V
    pip3 install vim-vint

before_script:
  - uname -a
  - nvim-nightly/nvim-linux64/bin/nvim --version
  - git clone https://github.com/junegunn/vader.vim.git --depth 1
  - git clone https://github.com/voldikss/vim-fnote.git --depth 1

script:
  - |
    nvim-nightly/nvim-linux64/bin/nvim -Nu <(cat << VIMRC
    set rtp+=vader.vim
    set rtp+=vim-fnote
    VIMRC) -c 'Vader! test/fnote.vader' > /dev/null
  - vint --color --style ./autoload ./plugin
